package-lock.json, package.json, shacl/dataset.jsonld, src/@types/rdf-validate-shacl.d.ts, src/server.ts, src/validator.ts, tsconfig.json
=> Validate dataset descriptions

package-lock.json, package.json, src/fetch.ts, src/server.ts
=> Extract fetch functionality

package-lock.json, package.json, src/fetch.ts, src/server.ts, src/store.ts, tsconfig.json
=> Store dataset descriptions

package-lock.json, package.json, src/server.ts, src/store.ts
* Execute HTTP request to GraphDB manually using node-fetch.
* See https://github.com/Ontotext-AD/graphdb.js/issues/123.
=> Work around GraphDB authentication bug

src/fetch.ts, src/server.ts
=> Support RDF at URL

src/server.ts
=> Add validation endpoint

src/server.ts
=> Log requests including submitted URLs

src/fetch.ts, src/server.ts
Fix #22.
* Transform Comunica errors but include original message.
=> Improve error handling

src/fetch.ts, src/server.ts, src/store.ts
=> Store registered URLs

package-lock.json, package.json, shacl/dcat.jsonld, src/dataset.ts, src/fetch.ts, src/query.ts, src/server.ts
Fix #35, fix #44.
* Add DCAT SHACL.
* Prevent license blank nodes by allowing IRIs only.
=> Store dataset descriptions as DCAT

package-lock.json, package.json, src/fetch.ts, src/main.ts, src/server.ts, test/http/invalid-dataset.json, test/http/valid-dataset.json, test/server.test.ts
Ref #39.
* Refactor to allow for easier dependency injection.
=> Test HTTP server

package-lock.json, package.json, shacl/dataset.jsonld, src/query.ts, test/datasets/dataset-schema-org-valid.jsonld, test/fetch.test.ts
=> Make dataset description optional

src/query.ts, test/datasets/catalog-dcat-invalid.jsonld, test/datasets/catalog-dcat-valid.jsonld, test/datasets/dataset-dcat-invalid.jsonld, test/datasets/dataset-dcat-valid.jsonld, test/datasets/datasets-dcat-invalid.jsonld, test/datasets/datasets-dcat-valid.jsonld, test/fetch.test.ts, test/validator.test.ts
Fix #26.
* Add tests.
* Fix some DCAT and dcterms predicates.
=> Support DCAT input

package-lock.json, package.json, src/server.ts, test/server.test.ts
* Fix #76.
* Make sure to either respond with a Dataset or an empty response.
This required making some responses empty, so add some logging
to keep observability.
=> Add content negotiation on validation results

Dockerfile, assets/api.yaml, package-lock.json, package.json, src/server.ts
Fix #68.
* Write OpenAPI spec ourselves rather than generating it from
fastify-swagger because the latter is too limited (it hardcodes,
for instance, Content-Type application/json).
=> Add OpenAPI docs

src/graphdb.ts
=> Fix duplicate registration results

shacl/dataset.jsonld, test/datasets/dataset-dcat-invalid.jsonld, test/datasets/dataset-http-schema-org-invalid.jsonld, test/datasets/dataset-schema-org-invalid.jsonld
Ref netwerk-digitaal-erfgoed/requirements-datasets#21.
=> Make distribution optional

src/query.ts, test/datasets/dataset-schema-org-valid.jsonld, test/fetch.test.ts
=> Simplify select query result handling

assets/api.yaml, src/main.ts, src/server.ts, src/validator.ts, test/server.test.ts
=> Add SHACL endpoint

shacl/register.ttl
* Only use name for PropertyShape, because they are not allowed on
NodeShape.
* On NodeShape, use rdfs:label instead.
=> Add SHACL names

shacl/register.ttl
changed severity and changed name and message
=> empty dataset in datacatalog now only warning

shacl/register.ttl, test/datasets/catalog-schema-org-invalid.jsonld, test/datasets/catalog-schema-org-no-dataset.jsonld, test/validator.test.ts
=> Validate catalog name

package-lock.json, package.json
See comunica/comunica#826.
Fix #201.
=> Update asynciterator to 3.2.0 to fix memory issue

shacl/register.ttl
=> Simplify SHACL

README.md, assets/api.yaml
=> Change name to Dataset Register

src/fetch.ts, src/server.ts
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables
=> Fix upgrade to TypeScript 4.4

src/query.ts
=> Store publisher separately

shacl/register.ttl, test/datasets/dataset-http-schema-org-invalid.jsonld, test/datasets/dataset-invalid-no-http-iri.jsonld, test/datasets/dataset-invalid-no-iri.jsonld, test/validator.test.ts
=> Require HTTP IRIs for dataset and publisher

src/query.ts, test/fetch.test.ts
=> Fix schema:keywords selection

shacl/register.ttl, test/datasets/dataset-schema-org-valid-plus-organization.jsonld, test/validator.test.ts
Fix https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/265
=> Relaxing the SHACL to allow separate schema:Organization items in graph

package-lock.json, package.json
npm run dev failed with:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module
/Users/david/src/netwerk-digitaal-erfgoed/dataset-register
/node_modules/node-fetch/src/index.js from
/Users/david/src/netwerk-digitaal-erfgoed/dataset-register/src
/graphdb.ts not supported.
```
=> Downgrade to node-fetch 2 to fix dev build

src/graphdb.ts
=> Serialize requests to GraphDB

jest.config.js, src/fetch.ts, src/query.ts, src/server.ts
=> Raise SPARQL LIMIT

jest.config.js, src/crawler.ts, src/fetch.ts, src/graphdb.ts, src/registration.ts, src/server.ts, test/crawler.test.ts, test/registration.test.ts
=> Fix how registration validity is stored

src/fetch.ts
=> Fix import

src/graphdb.ts
* The errors could make the application hang without properly crashing
it, so it would not be restarted by Kubernetes.
* Push the errors to the top level as rejected promises, so Fastify will
catch them.
* Fix #341.
=> Catch GraphDB errors

package-lock.json, package.json, test/datasets/dataset-schema-org-valid-microdata.html, test/datasets/dataset-schema-org-valid-rdfa.html, test/validator.test.ts
=> Test Microdata and RDFa

src/query.ts
=> fix: add mapping includedInDataCatalog

jest.config.js, shacl/register.ttl, src/query.ts, test/datasets/dataset-schema-org-valid.jsonld, test/fetch.test.ts
Fix #624
Ref netwerk-digitaal-erfgoed/requirements-datasets#74
=> feat: Accept person for creator and publisher

codemeta.json
Ref: https://github.com/CLARIAH/tool-discovery/issues/34
=> docs: URI fix in codemeta.json

jest.config.js, shacl/register.ttl, src/query.ts, test/datasets/catalog-dcat-valid.jsonld, test/datasets/dataset-dcat-valid.jsonld, test/datasets/datasets-dcat-valid.jsonld
* Make publisher required and creator optional, similarly to Schema.org.
* Require URI for creator/publisher.
Fix #696
Follow up #665
=> fix: Accept person in DCAT metadata too

shacl/register.ttl, src/query.ts, test/datasets/dataset-dcat-valid.jsonld, test/fetch.test.ts
=> feat: Support distribution dcat:mediaType

src/server.ts, test/server.test.ts
=> fix: No validation errors returned from POST

jest.config.js, shacl/register.ttl, src/validator.ts, test/datasets/catalog-schema-org-valid.jsonld
=> fix: Incorrect violations on child nodes

jest.config.js, src/crawler.ts, src/dataset.ts, src/fetch.ts, src/graphdb.ts, src/instrumentation.ts, src/main.ts, src/server.ts, src/validator.ts
Add file extension to relative imports as recommended in
https://www.typescriptlang.org/docs/handbook/esm-node.html
=> fix: Compatibility with ESM on Node 20

src/fetch.ts
=> fix: Pagination recursion

shacl/register.ttl
Relates to https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/864
Now only as warning, in the near future will become a validation.
=> Added check to contentUrl

src/query.ts, test/datasets/dataset-schema-org-valid.jsonld, test/fetch.test.ts
=> fix: Publisher not stored if type other than creator

jest.config.js, src/crawler.ts, src/dataset.ts, src/fetch.ts, src/graphdb.ts, src/server.ts, test/fetch.test.ts, test/mock.ts
=> fix: Reduce memory consumption

jest.config.js, src/literal.ts, src/query.ts, test/datasets/dataset-schema-org-valid.ttl, test/fetch.test.ts
=> feat: convert accessURL to IRI

src/query.ts
* Raise SPARQL LIMIT, which should be fine as we are streaming results.
* Use a subquery for a more representative LIMIT.
Fix #831
=> fix: Read more duplicate triples

shacl/register.ttl, src/query.ts, test/datasets/dataset-dcat-valid.jsonld, test/datasets/dataset-schema-org-valid.jsonld, test/fetch.test.ts
=> feat: Process spatial, temporal and genre

src/query.ts, test/fetch.test.ts
=> fix: Duplicate accessURL from Turtle

README.md, src/query.ts, test/datasets/dataset-dcat-valid.jsonld, test/datasets/dataset-schema-org-valid.jsonld, test/fetch.test.ts
=> feat: Add dct:conformsTo for SPARQL endpoints

jest.config.js, src/literal.ts, src/query.ts, test/datasets/dataset-dcat-valid.jsonld, test/fetch.test.ts
=> feat: Normalize license

apps/api/src/main.ts, apps/api/test/server.test.ts, apps/crawler/src/main.ts, package-lock.json, packages/core/package.json, packages/core/src/shacl-engine.d.ts, packages/core/src/validator.ts, packages/core/test/datasets/dataset-schema-org-multiple-alternate-names.ttl, packages/core/test/validator.test.ts, packages/core/vite.config.ts, rdf-validate-shacl.ttl, requirements/shacl.ttl, shacl-engine-no-details.ttl, shacl-engine-with-details.ttl
=> feat: return nested validation results

packages/core/src/shacl-engine.d.ts, packages/core/src/validator.ts, packages/core/test/datasets/dataset-schema-missing-publisher-class.ttl, packages/core/test/validator.test.ts, packages/core/vite.config.ts, requirements/shacl.ttl
=> fix: allow alternateName uniqueLang violations

packages/core/test/datasets/dataset-schema-org-invalid.jsonld, packages/core/test/validator.test.ts, requirements/index.bs, requirements/shacl.ttl
=> feat: verify dates

packages/core/src/validator.ts, packages/core/test/validator.test.ts, requirements/shacl.ttl
=> fix: some validation issues

packages/core/src/query.ts, packages/core/test/fetch.test.ts, packages/core/vite.config.ts
=> feat: query more properties

apps/api/src/server.ts
=> fix: allow CORS PUT requests
