Dockerfile
package.json

This way, we can have a single `shacl/dataset.jsonld` path
that works both in `npm run dev` and `npm start` (production).

Copy SHACL file using Docker instead

---

src/fetch.ts
src/server.ts

* Fix #23, fix #37. 
* Support both multiple schema:Datasets on the top-level and
a single schema:DataCatalog that contains one or more datasets.
* Use SPARQL SELECT rather than dereference to select only
the data we need.

Fetch all datasets from URL

---

.github/workflows/qa.yml
README.md
jest.config.js
package-lock.json
package.json
src/crawler.ts
src/graphdb.ts
src/registration.ts
src/server.ts
src/validator.ts
test/crawler.test.ts
tsconfig.json

* Fix #3.
* Schedule the crawler in Node itself rather than in
infrastructure (e.g. a Kubernetes CronJob) to have
fewer moving parts and to keep configuration in the
app (`CRAWLER_INTERVAL`) rather than the infrastructure.
* Only keep the last `dateRead` for Registrations.
* Keep the Registration's original `datePosted`.
* Extend GraphDB client for SPARQL queries. We cannot use
Comunica here because Comunica doesn't support setting
an Authentication header.
* Add Jest testing setup.

Crawl registered URLs

---

src/fetch.ts

Fix #50.
These quads still validate according to the SHACL,
so skip adding a quad if its binding value is empty.

Do not create quads with empty objects

---

.github/workflows/deploy.yml
README.md
src/server.ts

Ref #3.
By default, the crawler was scheduled for every hour.
However, when running multiple replicas of the application,
for instance on a Kubernetes cluster, the crawler ran on
each replica, duplicating effort needlessly.
Therefore, make the crawler dependent on a `CRAWLER_SCHEDULE`
environment variable. This way, we can enable the crawler only
on a separate Kubernetes deployment by setting the variable,
leaving the normal replicas to handle API requests only.

Enable crawler conditionally

---

src/crawler.ts
src/fetch.ts
src/graphdb.ts
src/registration.ts
src/server.ts
test/crawler.test.ts
test/mock.ts
test/server.test.ts

Fix #57.
* Extract mock stores for re-use in tests.
* Do first fetch as HEAD request for better performance.

Store HTTP status code when crawling

---

src/query.ts

Fix #72.
isIri doesn't play well with the `@vocab` notation:
```
"@context": {
"@vocab": "http://schema.org/"
},
```

Work around filter bug by using isBlank

---

shacl/dataset.jsonld
src/query.ts
src/validator.ts
test/datasets/dataset-http-schema-org-invalid.jsonld
test/datasets/dataset-http-schema-org-valid.jsonld
test/http/invalid-dataset.json
test/http/post-dataset.json
test/validator.test.ts

Fix #91.
For unknown reasons, our tests started failing on `https://schema.org`; we were querying `http://schema.org` but that wasn’t a problem before.

Support Schema.org at both HTTP and HTTPS

---

shacl/register.ttl
test/datasets/dataset-schema-org-valid.jsonld
test/fetch.test.ts

- relax date properties to include DateTime as schema.org suggests)
- date even relaxter (literal) + testcase
- increased expected size for changed dataset

relaxation of dates

---

shacl/register.ttl

dat**a**Modified wasn't used as dat**e**Modified is the property name

fixed typo

---

README.md
jest.config.js
src/crawler.ts
src/graphdb.ts
src/main.ts
src/registration.ts
src/server.ts
test/crawler.test.ts
test/fetch.test.ts
test/mock.ts

* Validate before querying the URL during crawl.
* Document property.
* Simplify Registration quad creation.
* Fix #112.

Store registration URL validity during crawl

---

src/crawler.ts

Try to reduce memory footprint of crawler by only moving on to the next
registration URL to be crawled when all writes to the RDF store have
finished.

Await writes to store when crawling

---

src/query.ts
test/datasets/dataset-schema-org-valid.jsonld
test/fetch.test.ts

* It seems the `?distribution` query variable is not global to the whole
query but only within its `OPTIONAL`. As a result of this, and because
datasets and distributions share some properties (such as
`schema:datePublished`), datasets were sometimes seen as
distributions too.
* Solve the issue by moving the `OPTIONAL`s inside the main distribution
`OPTIONAL`.

Fix distribution query optionals

---

shacl/register.ttl
test/datasets/dataset-http-schema-org-valid.ttl
test/validator.test.ts

* Use severity level `sh:Info` for recommendations.
* Split into two property shapes: one for description existence
(`sh:Info`) and one for validating the description if it exists
(`sh:Violation`).
* Lower `SchemaDistributionProperty` to `sh:Info` to support
distributions that have no description, which is optional.
* Ref #366.

Recommend description

---

shacl/register.ttl

Allow for multiple descriptions (usally, the same description in multiple languages)
Follow up #398. 
Fix #397.

Allow for multiple descriptions (removed maxCount)

---

src/server.ts
test/server.test.ts

With the automated upgrade to Fastify 4, the routes `/datasets/validate`
and `/shacl` returned empty HTTP responses. Follow the Fastify docs and
make sure to `return reply`. Add tests to prevent this in the future.

fix: Empty HTTP responses

---

shacl/register.ttl
src/query.ts
test/datasets/dataset-schema-org-valid.jsonld
test/fetch.test.ts

feat: Store publisher e-mail

---

shacl/register.ttl
test/datasets/dataset-dcat-valid.jsonld
test/fetch.test.ts

Both the Schema.org SHACl and the requirements already allow 
more than one format, so apply this to the DCAT SHACL too.

fix: Rate multiple distribution formats

---

jest.config.js
src/graphdb.ts

See https://github.com/node-fetch/node-fetch/issues/1735
Ref #832

fix: Disable keepalive for requests to GraphDB

---

src/literal.ts
src/query.ts
test/fetch.test.ts

* Because we follow the approach that logic should be written in SPARQL
instead of TypeScript where possible, do so for the date conversion too.
* We still need a template function in TypeScript for re-usability.
Fix #846

feat: Convert dates to xsd:date/xsd:dateTime

---

src/fetch.ts

fix: Don't cache potentially large HTTP responses

---

jest.config.js
src/fetch.ts
src/query.ts
test/datasets/dataset-dcat-valid.jsonld
test/datasets/dataset-schema-org-valid.jsonld
test/datasets/hydra-page1.jsonld
test/datasets/hydra-page2.jsonld
test/fetch.test.ts

* This seems to work now that we require a URI for publisher/creator.
* Replace transformation logic with a CONSTRUCT query.
* Simplify by replacing EventEmitter listeners with for await.

refactor: Use CONSTRUCT

---

jest.config.js
shacl/register.ttl
src/query.ts
test/datasets/catalog-dcat-valid.jsonld
test/datasets/dataset-dcat-valid.jsonld
test/datasets/datasets-dcat-valid.jsonld
test/fetch.test.ts

* Remove schema:fileFormat, which is superseded.
* Use dcat:mediaType, preferred for IANA types, instead of dct:format.
Ref netwerk-digitaal-erfgoed/dataset-register#1102

fix: Distribution media type mapping
